import { StyleSheet } from 'react-native';

export const songSliderStyles = StyleSheet.create({
  container: {
    padding: 0,
    borderRadius: 10,
    margin: 10,
    width: '90%',
  },
  slider: {
    width: '95%',
    borderRadius: 2,
    height: 10,
    marginVertical: 15,
  },
  timeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 10,
    marginTop: -10,
  },
  timeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  trackTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    textAlign: 'center',
    width: '100%',
    overflow: 'hidden',
    paddingHorizontal: 10,
    maxWidth: '100%',
    textAlignVertical: 'center',
    lineHeight: 20,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    userSelect: 'none',
  },
  outerSmall: {
    width: 4,
    height: 4,
    top: 6,
    borderRadius: 2,
    backgroundColor: '#003366',
    justifyContent: 'center',
    alignItems: 'center',
  },
  outerTrueSmall: {
    width: 8,
    height: 8,
    borderRadius: 2,
    backgroundColor: '#ABCDEF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerSmall: {
    width: 7,
    height: 7,
    borderRadius: 1,
    backgroundColor: '#223366',
  },
  innerTrueSmall: {
    width: 7,
    height: 7,
    borderRadius: 1,
    backgroundColor: '#334488',
  },
});
